// The 88 Victorian Legislative Assembly seats: 2022 result and map position.
//
// Winners, runners-up and margins are from the Victorian Electoral Commission's results for the
// 2022 State election and the 2023 Narracan District supplementary election:
// https://www.vec.vic.gov.au/results/state-election-results/2022-state-election-results
// © Victorian Electoral Commission, licensed under Creative Commons Attribution 4.0 International
// (https://creativecommons.org/licenses/by/4.0/). Keep this notice with the data.
//
// A margin is the winner's share of the last two candidates' votes after the distribution of
// preferences, less 50, rounded to one decimal place. Party codes, regions, contest names and map
// positions are this project's own. This is not an official record of the results.
import type { Seat } from './types';

export const SEATS: readonly Seat[] = [
  { name: 'Albert Park', region: 'Inner Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 11.2, contest: 'Labor v Coalition', col: 5, row: 6 },
  { name: 'Ashwood', region: 'Eastern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 6.2, contest: 'Labor v Coalition', col: 8, row: 5 },
  { name: 'Bass', region: 'Gippsland', winner: 'ALP', runnerUp: 'LIB', margin: 0.2, contest: 'Labor v Coalition', col: 10, row: 9 },
  { name: 'Bayswater', region: 'Outer East', winner: 'ALP', runnerUp: 'LIB', margin: 4.2, contest: 'Labor v Coalition', col: 10, row: 5 },
  { name: 'Bellarine', region: 'Geelong', winner: 'ALP', runnerUp: 'LIB', margin: 8.5, contest: 'Labor v Coalition', col: 3, row: 8 },
  { name: 'Benambra', region: 'Regional North', winner: 'LIB', runnerUp: 'IND', margin: 0.9, contest: 'Coalition v Independent', col: 10, row: 0 },
  { name: 'Bendigo East', region: 'Bendigo-Ballarat', winner: 'ALP', runnerUp: 'LIB', margin: 10.8, contest: 'Labor v Coalition', col: 3, row: 0 },
  { name: 'Bendigo West', region: 'Bendigo-Ballarat', winner: 'ALP', runnerUp: 'LIB', margin: 14.6, contest: 'Labor v Coalition', col: 2, row: 1 },
  { name: 'Bentleigh', region: 'Inner South-East', winner: 'ALP', runnerUp: 'LIB', margin: 8.0, contest: 'Labor v Coalition', col: 6, row: 7 },
  { name: 'Berwick', region: 'Outer South-East', winner: 'LIB', runnerUp: 'ALP', margin: 4.7, contest: 'Coalition v Labor', col: 10, row: 8 },
  { name: 'Box Hill', region: 'Eastern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 7.2, contest: 'Labor v Coalition', col: 9, row: 4 },
  { name: 'Brighton', region: 'Inner South-East', winner: 'LIB', runnerUp: 'ALP', margin: 5.1, contest: 'Coalition v Labor', col: 6, row: 6 },
  { name: 'Broadmeadows', region: 'Northern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 15.5, contest: 'Labor v Coalition', col: 5, row: 2 },
  { name: 'Brunswick', region: 'Inner Melbourne', winner: 'GRN', runnerUp: 'ALP', margin: 13.7, contest: 'Greens v Labor', col: 6, row: 4 },
  { name: 'Bulleen', region: 'Eastern Melbourne', winner: 'LIB', runnerUp: 'ALP', margin: 5.9, contest: 'Coalition v Labor', col: 8, row: 3 },
  { name: 'Bundoora', region: 'Northern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 12.7, contest: 'Labor v Coalition', col: 6, row: 1 },
  { name: 'Carrum', region: 'Bayside', winner: 'ALP', runnerUp: 'LIB', margin: 9.8, contest: 'Labor v Coalition', col: 8, row: 9 },
  { name: 'Caulfield', region: 'Inner South-East', winner: 'LIB', runnerUp: 'ALP', margin: 2.1, contest: 'Coalition v Labor', col: 7, row: 6 },
  { name: 'Clarinda', region: 'Inner South-East', winner: 'ALP', runnerUp: 'LIB', margin: 10.2, contest: 'Labor v Coalition', col: 7, row: 7 },
  { name: 'Cranbourne', region: 'Outer South-East', winner: 'ALP', runnerUp: 'LIB', margin: 9.0, contest: 'Labor v Coalition', col: 9, row: 9 },
  { name: 'Croydon', region: 'Outer East', winner: 'LIB', runnerUp: 'ALP', margin: 1.4, contest: 'Coalition v Labor', col: 11, row: 6 },
  { name: 'Dandenong', region: 'Inner South-East', winner: 'ALP', runnerUp: 'LIB', margin: 18.3, contest: 'Labor v Coalition', col: 8, row: 7 },
  { name: 'Eildon', region: 'Outer East', winner: 'LIB', runnerUp: 'ALP', margin: 7.0, contest: 'Coalition v Labor', col: 9, row: 2 },
  { name: 'Eltham', region: 'Eastern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 9.0, contest: 'Labor v Coalition', col: 8, row: 2 },
  { name: 'Essendon', region: 'Northern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 12.5, contest: 'Labor v Coalition', col: 5, row: 4 },
  { name: 'Eureka', region: 'Bendigo-Ballarat', winner: 'ALP', runnerUp: 'LIB', margin: 7.2, contest: 'Labor v Coalition', col: 1, row: 3 },
  { name: 'Euroa', region: 'Regional North', winner: 'NAT', runnerUp: 'ALP', margin: 9.9, contest: 'Coalition v Labor', col: 8, row: 1 },
  { name: 'Evelyn', region: 'Outer East', winner: 'LIB', runnerUp: 'ALP', margin: 5.4, contest: 'Coalition v Labor', col: 10, row: 2 },
  { name: 'Footscray', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'GRN', margin: 4.2, contest: 'Labor v Greens', col: 4, row: 5 },
  { name: 'Frankston', region: 'Bayside', winner: 'ALP', runnerUp: 'LIB', margin: 8.7, contest: 'Labor v Coalition', col: 8, row: 10 },
  { name: 'Geelong', region: 'Geelong', winner: 'ALP', runnerUp: 'LIB', margin: 14.7, contest: 'Labor v Coalition', col: 2, row: 8 },
  { name: 'Gippsland East', region: 'Gippsland', winner: 'NAT', runnerUp: 'ALP', margin: 24.6, contest: 'Coalition v Labor', col: 12, row: 7 },
  { name: 'Gippsland South', region: 'Gippsland', winner: 'NAT', runnerUp: 'ALP', margin: 15.6, contest: 'Coalition v Labor', col: 11, row: 9 },
  { name: 'Glen Waverley', region: 'Outer East', winner: 'ALP', runnerUp: 'LIB', margin: 3.3, contest: 'Labor v Coalition', col: 9, row: 5 },
  { name: 'Greenvale', region: 'Northern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 7.1, contest: 'Labor v Coalition', col: 4, row: 1 },
  { name: 'Hastings', region: 'Bayside', winner: 'ALP', runnerUp: 'LIB', margin: 1.4, contest: 'Labor v Coalition', col: 9, row: 10 },
  { name: 'Hawthorn', region: 'Eastern Melbourne', winner: 'LIB', runnerUp: 'ALP', margin: 1.7, contest: 'Coalition v Labor', col: 8, row: 4 },
  { name: 'Ivanhoe', region: 'Eastern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 12.8, contest: 'Labor v Coalition', col: 7, row: 2 },
  { name: 'Kalkallo', region: 'Northern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 16.5, contest: 'Labor v Coalition', col: 5, row: 0 },
  { name: 'Kew', region: 'Eastern Melbourne', winner: 'LIB', runnerUp: 'ALP', margin: 4.0, contest: 'Coalition v Labor', col: 7, row: 3 },
  { name: 'Kororoit', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 14.5, contest: 'Labor v Coalition', col: 3, row: 4 },
  { name: 'Lara', region: 'Geelong', winner: 'ALP', runnerUp: 'LIB', margin: 15.9, contest: 'Labor v Coalition', col: 1, row: 7 },
  { name: 'Laverton', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 18.4, contest: 'Labor v Coalition', col: 3, row: 5 },
  { name: 'Lowan', region: 'Regional West', winner: 'NAT', runnerUp: 'ALP', margin: 21.6, contest: 'Coalition v Labor', col: 0, row: 1 },
  { name: 'Macedon', region: 'Bendigo-Ballarat', winner: 'ALP', runnerUp: 'LIB', margin: 9.5, contest: 'Labor v Coalition', col: 3, row: 2 },
  { name: 'Malvern', region: 'Inner South-East', winner: 'LIB', runnerUp: 'ALP', margin: 8.1, contest: 'Coalition v Labor', col: 7, row: 5 },
  { name: 'Melbourne', region: 'Inner Melbourne', winner: 'GRN', runnerUp: 'ALP', margin: 10.2, contest: 'Greens v Labor', col: 5, row: 5 },
  { name: 'Melton', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 4.6, contest: 'Labor v Coalition', col: 2, row: 3 },
  { name: 'Mildura', region: 'Regional West', winner: 'NAT', runnerUp: 'IND', margin: 1.2, contest: 'Coalition v Independent', col: 1, row: 0 },
  { name: 'Mill Park', region: 'Northern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 11.6, contest: 'Labor v Coalition', col: 7, row: 0 },
  { name: 'Monbulk', region: 'Outer East', winner: 'ALP', runnerUp: 'LIB', margin: 7.6, contest: 'Labor v Coalition', col: 10, row: 7 },
  { name: 'Mordialloc', region: 'Bayside', winner: 'ALP', runnerUp: 'LIB', margin: 8.2, contest: 'Labor v Coalition', col: 8, row: 8 },
  { name: 'Mornington', region: 'Bayside', winner: 'LIB', runnerUp: 'IND', margin: 0.7, contest: 'Coalition v Independent', col: 7, row: 10 },
  { name: 'Morwell', region: 'Gippsland', winner: 'NAT', runnerUp: 'ALP', margin: 4.4, contest: 'Coalition v Labor', col: 12, row: 9 },
  { name: 'Mulgrave', region: 'Inner South-East', winner: 'ALP', runnerUp: 'IND', margin: 10.8, contest: 'Labor v Independent', col: 9, row: 6 },
  { name: 'Murray Plains', region: 'Regional North', winner: 'NAT', runnerUp: 'ALP', margin: 23.4, contest: 'Coalition v Labor', col: 2, row: 0 },
  { name: 'Narracan', region: 'Gippsland', winner: 'LIB', runnerUp: 'IND', margin: 13.0, contest: 'Coalition v Independent', col: 12, row: 8 },
  { name: 'Narre Warren North', region: 'Outer South-East', winner: 'ALP', runnerUp: 'LIB', margin: 8.7, contest: 'Labor v Coalition', col: 9, row: 7 },
  { name: 'Narre Warren South', region: 'Outer South-East', winner: 'ALP', runnerUp: 'LIB', margin: 8.3, contest: 'Labor v Coalition', col: 9, row: 8 },
  { name: 'Nepean', region: 'Bayside', winner: 'LIB', runnerUp: 'ALP', margin: 6.4, contest: 'Coalition v Labor', col: 6, row: 11 },
  { name: 'Niddrie', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 6.7, contest: 'Labor v Coalition', col: 4, row: 3 },
  { name: 'Northcote', region: 'Inner Melbourne', winner: 'ALP', runnerUp: 'GRN', margin: 0.2, contest: 'Labor v Greens', col: 6, row: 3 },
  { name: 'Oakleigh', region: 'Eastern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 13.5, contest: 'Labor v Coalition', col: 8, row: 6 },
  { name: 'Ovens Valley', region: 'Regional North', winner: 'NAT', runnerUp: 'ALP', margin: 17.8, contest: 'Coalition v Labor', col: 9, row: 1 },
  { name: 'Pakenham', region: 'Outer South-East', winner: 'ALP', runnerUp: 'LIB', margin: 0.4, contest: 'Labor v Coalition', col: 11, row: 8 },
  { name: 'Pascoe Vale', region: 'Northern Melbourne', winner: 'ALP', runnerUp: 'GRN', margin: 2.0, contest: 'Labor v Greens', col: 5, row: 3 },
  { name: 'Point Cook', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 8.3, contest: 'Labor v Coalition', col: 3, row: 6 },
  { name: 'Polwarth', region: 'Regional West', winner: 'LIB', runnerUp: 'ALP', margin: 1.8, contest: 'Coalition v Labor', col: 0, row: 3 },
  { name: 'Prahran', region: 'Inner Melbourne', winner: 'GRN', runnerUp: 'LIB', margin: 12.0, contest: 'Greens v Liberal', col: 6, row: 5 },
  { name: 'Preston', region: 'Northern Melbourne', winner: 'ALP', runnerUp: 'GRN', margin: 2.1, contest: 'Labor v Greens', col: 6, row: 2 },
  { name: 'Richmond', region: 'Inner Melbourne', winner: 'GRN', runnerUp: 'ALP', margin: 7.3, contest: 'Greens v Labor', col: 7, row: 4 },
  { name: 'Ringwood', region: 'Outer East', winner: 'ALP', runnerUp: 'LIB', margin: 7.5, contest: 'Labor v Coalition', col: 10, row: 4 },
  { name: 'Ripon', region: 'Bendigo-Ballarat', winner: 'ALP', runnerUp: 'LIB', margin: 3.0, contest: 'Labor v Coalition', col: 1, row: 1 },
  { name: 'Rowville', region: 'Outer South-East', winner: 'LIB', runnerUp: 'ALP', margin: 3.7, contest: 'Coalition v Labor', col: 10, row: 6 },
  { name: 'Sandringham', region: 'Inner South-East', winner: 'LIB', runnerUp: 'ALP', margin: 5.0, contest: 'Coalition v Labor', col: 7, row: 8 },
  { name: 'Shepparton', region: 'Regional North', winner: 'NAT', runnerUp: 'IND', margin: 6.8, contest: 'Coalition v Independent', col: 9, row: 0 },
  { name: 'South Barwon', region: 'Geelong', winner: 'ALP', runnerUp: 'LIB', margin: 9.8, contest: 'Labor v Coalition', col: 2, row: 9 },
  { name: 'South-West Coast', region: 'Regional West', winner: 'LIB', runnerUp: 'ALP', margin: 8.0, contest: 'Coalition v Labor', col: 1, row: 2 },
  { name: 'St Albans', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 9.6, contest: 'Labor v Coalition', col: 4, row: 4 },
  { name: 'Sunbury', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 6.4, contest: 'Labor v Coalition', col: 4, row: 2 },
  { name: 'Sydenham', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 8.8, contest: 'Labor v Coalition', col: 3, row: 3 },
  { name: 'Tarneit', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 12.3, contest: 'Labor v Coalition', col: 2, row: 5 },
  { name: 'Thomastown', region: 'Northern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 15.8, contest: 'Labor v Coalition', col: 5, row: 1 },
  { name: 'Warrandyte', region: 'Outer East', winner: 'LIB', runnerUp: 'ALP', margin: 4.3, contest: 'Coalition v Labor', col: 9, row: 3 },
  { name: 'Wendouree', region: 'Bendigo-Ballarat', winner: 'ALP', runnerUp: 'LIB', margin: 11.9, contest: 'Labor v Coalition', col: 2, row: 2 },
  { name: 'Werribee', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 10.9, contest: 'Labor v Coalition', col: 2, row: 6 },
  { name: 'Williamstown', region: 'Western Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 13.4, contest: 'Labor v Coalition', col: 4, row: 6 },
  { name: 'Yan Yean', region: 'Northern Melbourne', winner: 'ALP', runnerUp: 'LIB', margin: 4.3, contest: 'Labor v Coalition', col: 6, row: 0 },
];
